RECOVERY_VARIANT := twrp
TW_THEME := portrait_hdpi

BOARD_HAS_NO_REAL_SDCARD := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA := true
TARGET_KEYMASTER_WAIT_FOR_QSEE := true
TARGET_RECOVERY_DEVICE_DIRS += device/huawei/angler/twrp
TARGET_RECOVERY_QCOM_RTC_FIX := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_TWRPAPP := true
TW_INCLUDE_CRYPTO := true
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_USE_TOOLBOX := true
